### ISSUE TITLE
Einstein diffusion coefficient: the exported and the plotted data are not the same

### ISSUE THREAD

**Issue by MarcBrueck** [zincware/MDSuite#378] opened 2021-11-22 17:19 UTC
**Describe the bug**
The exported (saved in the experiment dictionary data) and the plotted data of the einstein diffusion msd (bokeh html plot) are not the same. The data differs by many orders of magnitude. This is probably the case because the plotted data is multiplied by by a time units factor (*self.experiment.units["time"]). That means the data that is plotted data is different from the saved data. I think this should not be the case otherewise the user has no idea which units the saved data is in.

**To Reproduce**
compute the einstein diffusion then look at the plotted and the saved data.

## Explanation
When plotting, we scale the data by the units of time.
https://github.com/zincware/MDSuite/blob/318f13694bf6532301195ddc637b798db846737a/mdsuite/calculators/calculator.py#L945-L948

**suggested Solution**
Save the data later when it is plotted

**Comment by PythonFZ** [comment] 2021-11-23 10:47
I can  change the code, but I don't know if this is expected behavior or truly a bug.

**Comment by SamTov** [comment] 2021-11-23 11:00
Yeah the plot was to keep the units on the y axis the same as you would get from the analysis but that should be removed I guess. Not the scaling on the x axis of course but the y need not be there.

**Comment by SamTov** [comment] 2021-11-23 11:00
Sorry... didn't mean to close it.

**Comment by MarcBrueck** [comment] 2021-11-23 11:39
It needs to be clear which units the data is in and as of right now the user has no  idea.

**Comment by SamTov** [comment] 2021-11-23 12:41
It should be in the units of msd if the time is not multiplied

**Comment by SamTov** [comment] 2021-11-25 00:31
So upon looking further it appears that this is by design. The issue is deciding what units to save as. When you plot it should ALWAYS be SI units. But the saved data is not necessarily which should be changed. We can enforce that this also becomes SI or we can have it be in the unit system of the simulation. My vote is for SI, please add your opinion @PythonFZ @MarcBrueck @Fratorhe.

**Comment by MarcBrueck** [comment] 2021-11-25 11:50
I also vote for SI, because then the data you get is the same as the data you see, which is convenient

**Comment by Fratorhe** [comment] 2021-11-25 12:33
For sure, we should be consistent for plotting and storing in the same units. 
However, I do not have a preference for the units. 
Would it possible to have problems with accuracy with SI units? ie. numbers that are extremely small or large which could cause a loss in precision? 
If so, I would vote to keep the units provided for the system (eg. metal, real, etc), this would also add consistency wrt the user input (same units in and out). 
However, if a Project contains different experiments and each of them is allowed to have a different unit system, then for sure we should use SI to avoid misunderstandings. 

In any case, we could give easy access to the unit conversion dictionaries. In such case, the final user could convert easily afterwards.

**Comment by SamTov** [comment] 2021-11-25 12:46
Okay so I think we can say SI is the way to go. My thought here is that, taking Einstein for an example, if you load the data and plot it, then take the fit of the line, you get your diffusion with NO additional pre-factor. Same for acfs. That removes all confusion.

This means though that we have to be careful with the data that is saved as usually it is multiplied by a pre-factor which includes a time scaling. So please be careful if someone looks at this before I get a chance to.

**Closed as completed** 2022-03-16 16:17 UTC
Labels: bug
